name: Render spec

on: [push, pull_request]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - name: Commit changes to main repository
      if: github.event.repository.fork == false && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' )
      uses: elstudio/actions-js-build/commit@v3
      with:
        commitMessage: "fixup: [spec] `npm run build`"
